### ISSUE TITLE
Demo App Todo

### ISSUE THREAD

**Issue by andychow326** [authgear/authgear-demo-app-rn#1]
ref https://github.com/authgear/authgear-server/issues/2208

## Screens
- [x] Configuration
- [x] Authentication
- [x] User panel
- [x] User info
 
### Configuration
  - [x] Add text input field for endpoint + client id
  - [x] Add label button for selecting color scheme
  - [x] Add switch for toggling token storage + share session options
  - [x] Storage to save config
  - [x] Navigate to Authenticate screen on save/cancel/back

### Authentication
  - [x] Find config in storage when open app
  - [x] Auto configure by storage config
  - [x] Navigate to Configuration screen if no config is found
  - [x] Add configuration button which navigate to Configuration screen
  - [x] Perform suitable authentication process for each button
    - [x] Signup
    - [x] Login
    - [x] Login with biometric 
    - [x] Login as guest
  - [x] Navigate to UserPanel screen if authenticated

### UserPanel
  - [x] Normal user view
  - [x] Guest user view
  - [x] Info icon button to show current config

### UserInfo (scrollable)
  - [x] All `UserInfo` fields
